Improvement - hover to highlight features
ABI-Software/mapintegratedvuer pull request #229
Opened 2024-07-03 22:10 UTC by ddjnw1yu

This is for the ticket - [Sidebar improvement - hover to show highlight features on map](https://www.wrike.com/open.htm?id=1408309810)

Removed the zoom-in marker action when hovering over a dataset.

Instead, all dataset-related features will now be highlighted.

<img width="600" alt="Screenshot 2024-07-04 at 9 59 24 AM" src="https://github.com/ABI-Software/mapintegratedvuer/assets/87633683/ed5f33dc-ae30-4d85-8d6c-0f2fe4e275ac">
<img width="600" alt="Screenshot 2024-07-04 at 9 59 44 AM" src="https://github.com/ABI-Software/mapintegratedvuer/assets/87633683/0a5f1852-ff4a-4f71-b283-761f6cf447cb">

2024-07-05 03:04 UTC, ddjnw1yu commented
Added highlight functionality for scaffold and flatmap as required.

<img width="600" alt="Screenshot 2024-07-05 at 3 02 36 PM" src="https://github.com/ABI-Software/mapintegratedvuer/assets/87633683/1231ed72-b093-42d2-b7ef-69012d98903d">

<img width="600" alt="Screenshot 2024-07-05 at 3 02 11 PM" src="https://github.com/ABI-Software/mapintegratedvuer/assets/87633683/1da9d539-4417-42e5-a326-311e9e9b8ca9">

2024-07-08 21:26 UTC, alan-wu requested changes
Looks good to me. Can you add the semi-colons to some of the end of line please?

2024-07-08 21:26 UTC, alan-wu commented on src/components/SplitFlow.vue
> +      const hoverOrgans = data && data.organs ? data.organs : []
Missing semi-colons here.

2024-07-08 21:26 UTC, alan-wu commented on src/mixins/ContentMixin.js
> +          mapImp?.changeHighlightedByName(hoverOrgans, "", false)
Missing semi-colons here.

2024-07-09 23:43 UTC, ddjnw1yu commented
Is there a time limit for the testing? Testing uses fixtures, no reason it will be aborted...

<img width="409" alt="Screenshot 2024-07-10 at 11 21 17 AM" src="https://github.com/ABI-Software/mapintegratedvuer/assets/87633683/30f93a2f-aba6-4845-843d-052badb310f5">

2024-07-10 04:10 UTC, alan-wu approved these changes
Looks good to me.

2024-07-10 04:11 UTC, merged